# Generated by Django 3.2.4 on 2021-06-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='nome insegnamento', max_length=100, null=True, verbose_name='insegnamento')),
            ],
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='nome dello studente', max_length=100, null=True, verbose_name='nome')),
                ('cognome', models.CharField(help_text='cognome dello studente', max_length=100, null=True, verbose_name='cognome')),
                ('email', models.EmailField(help_text='contatto mail dello studente', max_length=254, null=True, verbose_name='indirizzo email')),
                ('competenze', models.ManyToManyField(related_name='insegnato_a', to='registro_scolastico.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.DecimalField(decimal_places=1, help_text='valore del voto', max_digits=3, verbose_name='Voto')),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voti_presi', to='registro_scolastico.materia')),
                ('stud', models.ForeignKey(help_text='Studente che ha preso il voto', on_delete=django.db.models.deletion.CASCADE, related_name='risultati', to='registro_scolastico.studente', verbose_name='Studente')),
            ],
        ),
        migrations.CreateModel(
            name='Professore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='nome del professore', max_length=100, null=True, verbose_name='nome')),
                ('cognome', models.CharField(default='', help_text='cognome del professore', max_length=100, null=True, verbose_name='cognome')),
                ('email', models.EmailField(default='', help_text='contatto mail del professore', max_length=254, null=True, verbose_name='indirizzo email')),
                ('insegnamenti', models.ManyToManyField(related_name='insegnato_da', to='registro_scolastico.Materia')),
            ],
        ),
    ]
