# Generated by Django 3.2.5 on 2021-07-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_scolastico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name_plural': 'Materie'},
        ),
        migrations.AlterModelOptions(
            name='professore',
            options={'verbose_name_plural': 'Professori'},
        ),
        migrations.AlterModelOptions(
            name='studente',
            options={'verbose_name_plural': 'Studenti'},
        ),
        migrations.AlterModelOptions(
            name='voto',
            options={'verbose_name_plural': 'Voti'},
        ),
    ]
