# Generated by Django 3.1.3 on 2021-07-01 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro_scolastico', '0002_auto_20210701_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezione', models.CharField(choices=[['A', 'A'], ['B', 'B'], ['C', 'C'], ['D', 'D']], max_length=1, verbose_name='Sezione')),
                ('anno', models.IntegerField(choices=[[1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5']], max_length=1, verbose_name='Anno')),
            ],
            options={
                'verbose_name_plural': 'Aule',
            },
        ),
        migrations.AlterField(
            model_name='materia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='professore',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='professore',
            name='lezioni',
            field=models.ManyToManyField(blank=True, related_name='insegnanti', to='registro_scolastico.Aula'),
        ),
        migrations.AddField(
            model_name='studente',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunni', to='registro_scolastico.aula'),
        ),
    ]
